http://localhost:3001

###
GET http://localhost:3001/api/users/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0ODI0Mjc0MzM4YTQ3MTExZjBmMDciLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpZCI6NCwiaWF0IjoxNjQ5ODU1NDAzfQ.b4KZgWwJmeK2ilx-IQDLlttX87PWUq0ahBCKEWvgubQ

###
GET http://localhost:3001/api/users/625359480694a2e572214279

###
GET http://localhost:3001/api/users/handle/vp

###

DELETE  http://localhost:3001/api/users/6254827c74338a47111f0f08
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0ODI0Mjc0MzM4YTQ3MTExZjBmMDciLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGlhbiIsImhhbmRsZSI6Im5ld3BhbHR6X2JlbmV2b2xlbnQiLCJlbWFpbCI6InByZXNpZGVudEBuZXdwYWx0ei5lZHUiLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy9tZW4vMi5qcGciLCJpZCI6NCwiaWF0IjoxNjQ5ODU1NDAzfQ.b4KZgWwJmeK2ilx-IQDLlttX87PWUq0ahBCKEWvgubQ
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "firstName": "Donald",
  "lastName": "Christian",
  "handle": "newpaltz_benevolent",
  "password": "hugo",
  "email": "president@newpaltz.edu",
  "pic": "https://randomuser.me/api/portraits/men/2.jpg"
}

###
PATCH http://localhost:3001/api/users/6256ca79007f6090aeb0da17
Content-Type: application/json

{
  "lastName": "Putin III",
  "password": "Ukraine",
  "email": "save@ukraine.com"
}

###
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "email": "save@ukraine.com",
  "password": "Ukraine"
}

###
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "email": "president@newpaltz.edu",
  "password": "hugo"
}

###
POST http://localhost:3001/api/users/seed